### ISSUE TITLE
Please check if a new repo is necessary

### ISSUE THREAD

**Issue by pcav** [Mariosmsk/QCopycanvas#1]
Hi,
we are trying hard to keep the number of plugins reasonably low. Have you explored the possibility of merging your work into the original plugin by Bo? This would be the preferred option.
Thanks.

**Comment by Mariosmsk** [comment]
Hi @pcav, I have tried to communicate but I did not succeed. This plugin is only for QGIS 3.

**Comment by pcav** [comment]
Let me try to help.

**Comment by Mariosmsk** [comment]
Hi @pcav, are there any updates?

**Comment by pcav** [comment]
Indeed, no reply, quite strange. Let's go on with the publication, ready to go back in case Bo will reply.
